version: "2.4"
services:
  postgres:
    image: postgres:latest
    build: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: posts_db
    volumes:
    - ./api:/api
    healthcheck:
      test: POSTGRES_PASSWORD=pass pg_isready -q -U user -d posts_db
  api:
    build:
      context: api
    command: python main.py
    ports:
      - 8080:8080
    depends_on:
      - postgres
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  logstash:
    build:
      context: logstash
    depends_on:
      - elasticsearch
      - postgres





